### ISSUE TITLE
Idea: Reporting sensor battery value

### ISSUE THREAD

**Issue by Gabor9** [Frans-Willem/AqaraHub#13]
For battery operated type of sensors the battery seems reported in Voltage value in the beginning of 0xFF01 xiaomi specific data stream like : index: 1, type: uint16, value: (C7 0B) = 3015 in milliVolts (3.015Volt) 
Suggested range for the percentage calculation is 2.4V .. 3V

**Comment by Frans-Willem** [comment]
The main idea in AqaraHub is just to pass on whatever is received from the Zigbee network to MQTT, and leave post-processing to whomever is listening on the other side. e.g. the temperature value requires division by 100. I've deliberately done it this way, because it means that it will likely also work with sensors that I do not own myself, and it means that the main project doesn't need a lot of sensor-specific code.

With the battery stuff, it appears the Xiaomi sensors do not report a percentage, but rather a voltage, so preferably I'd like to publish that as-is to the MQTT server. In your OpenHAB installation you could then choose to either report the battery voltage as-is, or add a transformation script to convert it to a percentage :)

With Xiaomi devices reporting the Basic/0xFF02 attribute, which is properly formatted as a zigbee structure, it's already converted rather nicely to a JSON structure that you can easily pick out the battery voltage from. An example being the lumi.sensor_magnet device:
```
AqaraHub/report/158D0001876247/1/Basic/0xFF02 {"type":"struct","value":[{"type":"bool","value":true},{"type":"uint16","value":3015},{"type":"uint16","value":424},{"type":"uint40","value":0},{"type":"uint16","value":31},{"type":"uint8","value":92}]}
```
The second value in the array is likely the battery voltage and I suspect the last item to be a battery percentage (but I'm not sure about this one yet!)

Older(?) devices appear to be reporting the Basic/0xFF01 attribute, marked as a string value, and using some kind of custom binary encoding. I think the best course of action here is to add an exception in AqaraHub for this attribute only, parse the values, and report them as in the 0xFF02 attribute.
An example here is the lumi.sensor_ht:
```
AqaraHub/report/158D0001A2B6A0/1/Basic/0xFF01 {"type":"string","value":"\u0001!�\u000b\u0004!�\u0001\u0005!\u000f\u0000\u0006$\u0001\u0000\u0000\u0000\u0000d)�\u0006e!�\u0012\n!\u000b\u001b"}
```

I'll leave this issue, together with https://github.com/Frans-Willem/AqaraHub/issues/10, open and will try to pick them up as soon as possible. However, my main focus at this point is to get commands from MQTT to the Xiaomi devices working, so we can control the smart plug or the curtain motors :)

**Comment by Gabor9** [comment]
Great idea to convert 0xFF01 structure readable and pass it for parsing.
My lumi.plugs are eager waiting to receive mqtt commands too :)  I just recently realized this device can act as zigbee Repeater for other sensors, self creating mesh network.
